import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.scss";
import piles from "@/styles/Test.module.scss";

import Post from "../components/Post/index";
import PostForm from "../components/PostForm/index";
import fox from "../assets/images/fox.svg";
import Fox from "../assets/images/fox.svg";
import Logo from "../assets/images/logo.svg";
import Bio from "../components/Bio/index";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <main className={styles.main}>
          <div className={styles.description}>
            <Bio
              headshot="https://pbs.twimg.com/profile_images/1547747685817454592/--aLCZbS_400x400.jpg"
              name="Deinde Dawodu"
              tagline="Helping myself learn by doing"
              role="Creative Technologist @ Paradise Objects"
            />
            <ul className={styles.posts}>
              <li>
                <Post content="Hey I'am a new post" date="2/26/2023" />
              </li>
              <li>
                <Post
                  content="I’m working in Figma trying to design a new website that shows
                  all of my tweets!"
                  date="1/18/2023"
                />
              </li>
              <li>
                <Post
                  content="I’m working in Figma trying to design a new website that shows
                  all of my tweets!"
                  date="1/18/2023"
                />
              </li>
            </ul>
            <PostForm label="Click Me" />
          </div>
        </main>
      </div>
    </div>
  );
}
